import type { Metadata } from "next";
import { Inter  } from "next/font/google";

import { cn } from "@/lib/utils";
import "./globals.css";
import SessionProvider from "./provider/SessionProvider";
import { getServerSession } from "next-auth";
import { AuthProvider } from "./context/AuthContext";
import { Toaster } from "@/components/ui/toaster";
import QueryProvider from "./provider/QueryProvider";


 const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Platform  0.0.4",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <SessionProvider session={session} basePath="/pnev/api/auth">
      <QueryProvider>
        <AuthProvider>
          <html lang="en">
            <body className={inter.className}>
              {children}
              <Toaster />{" "}
            </body>
          </html>
        </AuthProvider>
      </QueryProvider>
    </SessionProvider>
  );
}
